words_with_hints = [
    ("react", "A popular JavaScript library for building UIs"),
    ("javascript", "The programming language of the web"),
    ("hangman", "A classic word guessing game"),
    ("framework", "A structure used to build software"),
    ("component", "Reusable piece in a React app"),
    ("state", "A way to store changing data in React"),
    ("props", "Used to pass data in React"),
    ("node", "JavaScript runtime built on Chrome’s V8 engine"),
    ("express", "Fast Node.js web framework"),
    ("vite", "Fast frontend build tool"),
    ("html", "Markup language for creating web pages"),
    ("css", "Style language used with HTML"),
    ("frontend", "The part of a website you see"),
    ("backend", "The part of a website you don't see"),
    ("database", "Stores and organizes digital data"),
    ("api", "Interface for communicating between systems"),
    ("json", "Lightweight data-interchange format"),
    ("ajax", "Technique for asynchronous web requests"),
    ("dom", "Document Object Model"),
    ("query", "A request for data or information"),
    ("variable", "Used to store data in programming"),
    ("function", "Block of code designed to perform a task"),
    ("loop", "Repeats a block of code"),
    ("condition", "Used to make decisions in code"),
    ("array", "A list-like data structure"),
    ("object", "Data structure with key-value pairs"),
    ("class", "Blueprint for creating objects"),
    ("inheritance", "Mechanism for sharing behavior in OOP"),
    ("interface", "Defines a contract in TypeScript"),
    ("typescript", "JavaScript with types")
]
